# Generated by Django 5.2 on 2025-04-12 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Idiom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phrase",
                    models.CharField(
                        max_length=200, unique=True, verbose_name="Идиома"
                    ),
                ),
                (
                    "definition",
                    models.TextField(verbose_name="Определение на английском"),
                ),
                ("example", models.TextField(verbose_name="Пример употребления")),
                (
                    "translation",
                    models.TextField(blank=True, verbose_name="Перевод на русский"),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[("B2", "B2"), ("C1", "C1"), ("C2", "C2")],
                        default="B2",
                        max_length=2,
                        verbose_name="Уровень",
                    ),
                ),
            ],
        ),
    ]
